---
- hosts: all
  gather_facts: yes
  tasks:
  - name: configure Windows DNS
    win_dns_client:
      adapter_names: "*"
      ipv4_addresses:
       - "{{ dc_ip }}"
  - name: Debug DNS servers
    win_shell: "ipconfig /all"
  - name: Join "{{ domain_name }}" Domain
    win_shell: add-computer -domainname "{{ domain_name }}" -credential (New-Object System.Management.Automation.PSCredential ("{{ domain_user }}", (ConvertTo-SecureString "{{ domain_pw }}" -AsPlainText -Force)))
    register: adjoin_result

  - name: "Reboot"
    win_reboot:
    when: adjoin_result.changed                                
