---
- hosts: localhost
  tasks:
    - name: Create a virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ rg }}"
        address_prefixes_cidr:
          - "{{ subnet }}"
        dns_servers:
          - "{{ dns }}"
        tags:
          testing: testing
          delete: on-exit
