---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a virtual network
      azure_rm_virtualnetwork:
        client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
        secret: "{{ lookup('env', 'AZURE_SECRET') }}"
        subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
        name: "{{ net_name }}"
        resource_group: "{{ rg }}"
        address_prefixes_cidr:
          - "{{ subnet }}"
        dns_servers:
          - "{{ dns }}"
        tags:
          testing: testing
          delete: on-exit
