---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Get facts for one network interface
    azure_rm_networkinterface:
      client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
      tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
      secret: "{{ lookup('env', 'AZURE_SECRET') }}"
      subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
      resource_group: "{{ rg }}"
      name: "{{ inf_name }}"
      private_ip_address: "{{ dc_ip }}"
      private_ip_allocation_method: Static
