---
- name: Debug event target
  hosts: localhost
  connection: local
  roles:
  - syncrou.manageiq-automate
  tasks:
  - name: "Get the full list of Objects"
    manageiq_automate:
      workspace: "{{ workspace }}"
      get_object_names: yes
