---
- hosts: all
  tasks:
  - name: Launch Nessus Scan
    uri:
      url: "https://://{{ nessus_server }}":{{ port }}/scans/{{ scan_id }}/launch"
      method: GET
      return_content: yes
      user: admin
      password: "{{ nessus_password }}"
      validate_certs: no
      body_format: json
      headers:
        Content-Type: "application/json"
      body:
        alt_targets: "{{ ansible_default_ipv4.address }}"
