---
- hosts: localhost
  tasks:
  - rds:
      command: create
      instance_name: "{{ name }}"
      db_engine: "{{ engine }}"
      size: "{{ size }}"
      instance_type: "{{ type }}"
      username: "{{ user }}"
      region: "{{ region }}
      password: "{{ password }}"
      tags:
        Environment: testing
        Application: cms

