---
- hosts: localhost
  tasks:
  - rds:
      command: create
      instance_name: "{{ name }}"
      db_engine: MySQL
      size: "{{ size }}"
      instance_type: db.m1.small
      username: mysql_admin
      region: us-east-1
      password: 1nsecure
      tags:
        Environment: testing
        Application: cms

