---
- hosts: localhost
  tasks:
  - name: create new RDS DB instance 
    rds:
      command: create
      instance_name: "{{ db_name }}"
      db_engine: "{{ engine }}"
      size: "{{ size }}"
      instance_type: "{{ type }}"
      username: "{{ user }}"
      region: "{{ region }}"
      password: "{{ password }}"
      tags:
        Environment: testing
        Application: cms

  - name: Create CloudForms Generic object instance
    uri:
      url: "https://localhost/api/generic_objects"
      method: POST
      user: admin
      password: "{{ cf_password }}"
      validate_certs: no
      headers:
        Content-Type:  application/json
      body_format: json
      body:
        action: create
        name: "API Test"
        generic_object_definition:
          href: "https://localhost/api/generic_object_definitions/46000000000001"
        property_attributes:
          engine: "{{ engine }}"
          type: "{{ type }}"
          region: "{{ region }}"
          username: "{{ user }}"
          size: "{{ size }}"
          name: "{{ db_name }}"
