---
- hosts: localhost
  connection: local
  gather_facts: no
  vars: 
    vm_name: web1
    web: true
    haproxy: false
  roles:
    - {role: 'buildrhv'}

- hosts: localhost
  connection: local
  gather_facts: no
  vars: 
    vm_name: web2
    web: true
    haproxy: false
  roles:
    - {role: 'buildrhv'}

- hosts: localhost
  connection: local
  gather_facts: no
  vars: 
    vm_name: haproxy
    web: false
    haproxy: true
  roles:
    - {role: 'buildrhv'}
