---
- hosts: localhost
  tasks:
  - name: Create initial Datacenter object in vSphere
    vmware_datacenter:
      hostname: '{{ vsphere_host }}' 
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_pw }}'
      validate_certs: False
      datacenter_name: '{{ datacenter }}'
      state: present

  - name: Create vSphere cluster
    vmware_cluster:
      hostname: '{{ vsphere_host }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_pw }}'
      validate_certs: False
      datacenter_name: '{{ datacenter }}'
      cluster_name: '{{ cluster }}'

  - name: Add Hosts
    vmware_host:
      hostname: '{{ vsphere_host }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_pw }}'
      validate_certs: False
      datacenter_name: '{{ datacenter }}'
      cluster_name: '{{ cluster }}'
      esxi_hostname: '{{ item }}' 
      esxi_username: '{{ esxi_user }}'
      esxi_password: '{{ esxi_pw }}'
    delegate_to: localhost
    with_items: '{{ esx_hosts }}'
